# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd = {
      availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
      kernelModules = [ "dm-snapshot" ];
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-label/SYSTEM";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/BOOT";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-label/HOME";
      fsType = "ext4";
    };

  swapDevices = [ ];

  powerManagement = {
    cpuFreqGovernor = lib.mkDefault "powersave";
  };

  hardware = {
    cpu = {
      intel = {
         updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
      };
    };
  };

  networking = {
    hostName = "legion";
    useDHCP = false;
    interfaces = {
      enp66s0 = {
        useDHCP = true;
      };
      wlp0s20f3 = {
        useDHCP = true;
      };
    };
  };
   
  services = {
    xserver= {
      videoDrivers = ["nvidia"];
      dpi = 96;
    };
    
    fstrim = {
      enable = true;
      interval = "weekly";
    };
  };

}
